---
- name: Creacion de database en PostgreSQL
  hosts: all
  become: true
  vars:
    db_name: pruebadb
  tasks:
    - name: Utility present
      ansible.builtin.package:
        name: python3-psycopg2
        state: present

    - name: Crear/Eliminar database
      community.postgresql.postgresql_db:
        state: present #Si queremos borrar la databse debemos cambiar el estado a absent
        name: "{{ db_name }}"
      become: true
      become_user: postgres