---
- name: postgresql demo
  hosts: all
  become: true
  vars:
    db_user: user
    db_name: ejemplodb
  tasks:
    - name: Utility present
      ansible.builtin.package:
        name: python3-psycopg2
        state: present
  
    - name: Elevar privilegios
      community.postgresql.postgresql_privs:
        type: database
        database: "{{ db_name }}"
        roles: "{{ db_user }}"
        grant_option: false
        privs: all
      become: true
      become_user: postgres