---
- name: Instalar postgreSQL
  hosts: ubuntu
  become: true
  tasks:
    - name: Instalar paquetes
      ansible.builtin.yum:
        name:
          - postgresql
          - postgresql-server
          - postgresql-contrib
          - postgresql-libs
          - python3-psycopg2
        state: present

    - name: Comprobar si PostgreSQL está iniciado
      ansible.builtin.stat:
        path: "/var/lib/pgsql/data/pg_hba.conf"
      register: postgres_data

    - name: Iniciar PostgreSQL
      ansible.builtin.shell: "postgresql-setup initdb"
      when: not postgres_data.stat.exists

    - name: Iniciar y habilitar el servicio
      ansible.builtin.service: Ansible For PostgreSQL 1004
      name: postgresql
      state: started
      enabled: true